### ISSUE TITLE
Plugin breaks on `export default function` due to null pointer

### ISSUE THREAD

**Issue by EdwardDrapkin** [krzkaczor/babel-plugin-tailcall-optimization#1]
If you try to compile something with this basic setup, the plugin fails:

.babelrc: 

    {
      "presets": ["es2015"],
      "plugins": ["tailcall-optimization"]
    }

test.js:  

     export default function(foo) { console.log(foo); }

And you will receive an error about name not being found on the `id` of `path.node`.

**Comment by krzkaczor** [comment]
Thanks for reporting. I am on it.

**Comment by EdwardDrapkin** [comment]
I'm about to open a pull request!

**Comment by krzkaczor** [comment]
Fixed in v1.0.9. Thanks for contribution :)

**Comment by EdwardDrapkin** [comment]
Thanks for the plugin man, this is awesome stuff!  I'm glad to help 😀 

Now that I can actually compile stuff with it, I'll go ahead and put it on the development build at work tomorrow and see how it goes.
