### ISSUE TITLE
Didn't ES2015 introduce tail call optimization?

### ISSUE THREAD

**Issue by MichalZalecki** [krzkaczor/babel-plugin-tailcall-optimization#10]
Krzysztof, can you shed some light why plugins' optimization is a thing? I'm refering to [introduced optimizations](http://2ality.com/2015/06/tail-call-optimization.html).

**Comment by xtuc** [comment]
Some JavaScript engines and Babel have disabled the tail call optimization because of its complexity.

**Comment by krzkaczor** [comment]
@MichalZalecki as you can see on [compatibility table](https://kangax.github.io/compat-table/es6/#test-proper_tail_calls_(tail_call_optimisation)), still in 2017 almost no major js engine supports TCO. I am not sure why is that... probably full compliance with spec is waaaay harder than what this plugin tries to achieve. 

@xtuc is right. Babel used to have TCO (i guess in version 5.x) but it was quite buggy. I found some old issues and tried to create workarounds for them (mostly for function scope). My workaround was simply not to attempt to optimize it at all :D

**Comment by MichalZalecki** [comment]
@xtuc @krzkaczor Thanks guys for a quick response 👏
