### ISSUE TITLE
conditional operator not supported

### ISSUE THREAD

**Issue by DanHodges** [krzkaczor/babel-plugin-tailcall-optimization#12]
Great plugin. Thanks for writing. Are conditionals supposed to be supported?

This sample input
```
const countJumps = (list, index, step) => {
  const value = list.get(index);

  if (value === undefined) return step;

  return countJumps(list.set(index, value + 1), index + value, step + 1);
};

const countJumpsTernary = (list, index, step) => {
  const value = list.get(index);

  return value === undefined
    ? step
    : countJumps(list.set(index, value + 1), index + value, step + 1);
};
```
Produces this output
```
const countJumps = (list, index, step) => {
  var _repeat = true;

  var _list, _index, _step;

  while (_repeat) {
    _repeat = false;

    const value = list.get(index);

    if (value === undefined) return step;

    _list = list.set(index, value + 1);
    _index = index + value;
    _step = step + 1;
    list = _list;
    index = _index;
    step = _step;
    _repeat = true;
    continue;
  }
};

const countJumpsTernary = (list, index, step) => {
  const value = list.get(index);

  return value === undefined ? step : countJumps(list.set(index, value + 1), index + value, step + 1);
};
```
Is this the expected behavior? 
I'm using a fresh install of babel with `"tailcall-optimization"` as my only plugin.

**Comment by acthp** [comment]
I think your second example is wrong, because it's not recursive.

But, yeah, I don't think the ternary operator is supported. I'd really like it to be supported, as many algorithms are more naturally written that way. I expect it wouldn't be too hard: I would guess you could convert the ternary to an if/else prior to testing if the function is recursive, and bail out if it's not.

**Comment by DanHodges** [comment]
So sorry. When I typed up that example I renamed some things at the last moment and forgot to rename countJumps to countJumpsTernary in that last line.

You are correct, that was wrong.
I know there's a plugin that transforms ternary to if/else, so I'll experiment with that as well. Thanks for the feedback 👍 
```
const countJumps = (list, index, step) => {
  const value = list.get(index);

  if (value === undefined) return step;

  return countJumps(list.set(index, value + 1), index + value, step + 1);
};

const countJumpsTernary = (list, index, step) => {
  const value = list.get(index);

  return value === undefined
    ? step
    : countJumpsTernary(list.set(index, value + 1), index + value, step + 1);
};
```
Produces
```
const countJumps = (list, index, step) => {
  var _repeat3 = true;

  var _list3, _index3, _step3;

  while (_repeat3) {
    _repeat3 = false;

    const value = list.get(index);

    if (value === undefined) return step;

    _list3 = list.set(index, value + 1);
    _index3 = index + value;
    _step3 = step + 1;
    list = _list3;
    index = _index3;
    step = _step3;
    _repeat3 = true;
    continue;
  }
};

const countJumpsTernary = (list, index, step) => {
  const value = list.get(index);

  return value === undefined ? step : countJumpsTernary(list.set(index, value + 1), index + value, step + 1);
};
```

**Comment by DanHodges** [comment]
Ah shucks, just realized that `babel-plugin-transform-ternary-to-if-else` transforms a ternary to an if else nested in an IIFE so scratch that.

**Comment by krzkaczor** [comment]
Hey @DanHodges @acthp Support for ternary landed in https://github.com/krzkaczor/babel-plugin-tailcall-optimization/pull/11 I am gonna release new version to NPM now. Stay tight.

**Comment by krzkaczor** [comment]
Okay `1.0.12` is out. Please reopen this issue if it didn't solve your problems.

**Comment by acthp** [comment]
This is awesome! Thanks!

I just tested with this:

```
function fact(n, acc = 1) {
	return n > 1 ? fact(n - 1, n * acc) : acc;
}
```
and with some nested ternary expressions, which have all worked perfectly.

I notice that if I write it as an arrow function, it doesn't get converted:

```
var fact = (n, acc = 1) => n > 1 ? fact(n - 1, n * acc) : acc;
```

output:
```
var fact = function fact(n) {
  var acc = arguments.length > 1 && arguments[1] !== undefined ? arguments[1] : 1;
  return n > 1 ? fact(n - 1, n * acc) : acc;
};
```

while if I write an arrow function with ```if```/```else```, it does get converted:

```
var fact = (n, acc = 1) => {
	if (n > 1) {
		return fact(n - 1, n * acc);
	}
	return acc;
};
```

output:

```
var fact = function fact(n) {
	var acc = arguments.length > 1 && arguments[1] !== undefined ? arguments[1] : 1;
	var _repeat = true;

	var _n, _acc;

	while (_repeat) {
		_repeat = false;

		if (n > 1) {
			_n = n - 1;
			_acc = n * acc;
			n = _n;
			acc = _acc;
			_repeat = true;
			continue;
		}
		return acc;
	}
};
```

Maybe an ordering issue in the transform?
