### ISSUE TITLE
Support babel 7

### ISSUE THREAD

**Issue by graingert** [krzkaczor/babel-plugin-tailcall-optimization#13]

**Comment by xtuc** [comment]
Please let me know of I can help with something about that.

**Comment by krzkaczor** [comment]
@xtuc is there a nice migration guide somewhere? or could you point me to another not-so-complicated plugin that start supporting babel@7 so i can take a closer look at diff? Thanks :)

**Comment by xtuc** [comment]
We have http://babeljs.io/blog/2017/03/01/upgrade-to-babel-7-for-tool-authors but it's not really up-to-date.

I would suggest you using https://github.com/babel/babel-upgrade.

**Comment by mfila** [comment]
I've tried to upgrade the plugin to babel 7. Tests still pass. See https://github.com/mfila/babel-plugin-tailcall-optimization/tree/babel7.

All it takes was:
1. removing old packages
2. installing new ones (replacing es2015 preset with env)
3. upgrading to @babel namespace in a couple of places

**Comment by xtuc** [comment]
@mfila, yeah thanks that looks good!

**Comment by mfila** [comment]
@krzkaczor yes... an alternative branch'd be great!

**Comment by mfila** [comment]
I've updated my branch to use Babel 7 beta.56 before making the PR

**Comment by krzkaczor** [comment]
@mfila thanks so much for your contribution!
