### ISSUE TITLE
Can a Babel 7 release be awaited?

### ISSUE THREAD

**Issue by sinkaszab** [krzkaczor/babel-plugin-tailcall-optimization#19]
- In #13 efforts have been made to support Babel 7.
- However no release on NPM registry is to be found.
- Cannot install `next` branch directly from git repo via NPM, because either the build step or it is me who is missing a step here. (I don't consider this a problem that generated code is missing from the git repo, just a fact.)

**Questions:**

1. Can I hope for a Babel 7 compatible NPM release? (And when?)
2. Should I fork & publish one if I need it? (Would you mind it?)

**Comment by krzkaczor** [comment]
@sinkaszab oh, sorry for that. I am gonna release it in few minutes 👍

**Comment by sinkaszab** [comment]
Great, thanks a lot!

**Comment by krzkaczor** [comment]
@sinkaszab, released as `babel-plugin-tailcall-optimization@2.0.0`

**Comment by sinkaszab** [comment]
Works as expected, great, thanks again!
