### ISSUE TITLE
Doesn't handle the ternary operator

### ISSUE THREAD

**Issue by chocolateboy** [krzkaczor/babel-plugin-tailcall-optimization#9]
OS: Linux (Arch)
Node.js: v7.4.0
babel-cli: 6.23.0 (babel-core 6.23.1)
babel-plugin-tailcall-optimization: 1.0.11

---
 
The if/else case is correctly handled e.g.:

### Input

```javascript
function factorial (n) {
    return factorialAccum(1, n)
}

function factorialAccum (accum, n) {
    if (n === 1) {
        return accum
    } else {
        return factorialAccum(accum * n, n - 1)
    }
}

console.log(factorial(5))
```

### Output

```javascript
"use strict";

function factorial(n) {
    return factorialAccum(1, n);
}

function factorialAccum(accum, n) {
    var _repeat = true;

    var _accum, _n;

    while (_repeat) {
        _repeat = false;

        if (n === 1) {
            return accum;
        } else {
            _accum = accum * n;
            _n = n - 1;
            accum = _accum;
            n = _n;
            _repeat = true;
            continue;
        }
    }
}

console.log(factorial(5));
```

But the equivalent code written with the ternary operator isn't transformed:

### Input

```javascript
function factorial (n) {
    return factorialAccum(1, n)
}

function factorialAccum (accum, n) {
    return n === 1 ? accum : factorialAccum(accum * n, n - 1)
}

console.log(factorial(5))
```

### Output

```javascript
"use strict";

function factorial(n) {
    return factorialAccum(1, n);
}

function factorialAccum(accum, n) {
    return n === 1 ? accum : factorialAccum(accum * n, n - 1);
}

console.log(factorial(5));
```

**Comment by krzkaczor** [comment]
@chocolateboy Thank you so much for detailed bug report. 

The problem is in [findTailCalls.js](https://github.com/krzkaczor/babel-plugin-tailcall-optimization/blob/master/src/findTailCalls.js#L3). We need to add an additional check for expressions that could lead to TC. Probably it's good idea to rewrite ternary operator to if statement after detecting TC.

I can provide some more details/ideas if you want to work on the patch :)

**Comment by chocolateboy** [comment]
I probably don't have time at the moment, but feel free in case I do or someone else wants to have a go :-)
